# Uncomment the next line to define a global platform for your project
# platform :ios, '14.3'

target 'RealEstateApp' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealEstateApp
	
	target 'RealEstateAppTests' do
	inherit! :search_paths
	#Pods for testing
	
	
	pod 'SnapshotTesting'
	end

end











