# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ViewCodeChallenge-RealEstate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewCodeChallenge-RealEstate
	
	target 'ViewCodeChallenge-RealEstateTests' do
	inherit! :search_paths
	#Pods for testing

	pod 'SnapshotTesting'
	pod 'SwiftGen'
	end

end
